### ISSUE TITLE
ee_check() error, Python version 3.10 is recognized as Python 3.1

### ISSUE THREAD

**Issue by jwilliamrozelle** [r-spatial/rgee#268] opened 2022-06-22 02:39 UTC
* rgee version: 1.1.3
* R version: 4.1.2
* Operating System: Windows

when I run ee_check, I get the error:

`(*)  Python version
√ [Ok] C:/Users/jwrozelle/AppData/Local/Programs/Python/Python310/python.exe v3.1
Error in ee_check_python(quiet = quiet) : rgee needs Python 3.5 >=`

Python 3.10 should satisfy this requirement, but looks like the check is getting hung up on the weird python version numbering where 3.10 != 3.1

**Comment by csaybar** [comment] 2022-06-23 15:31
Hi @jwilliamrozelle thank you for opening this issue!

This was an embarrassing bug from my side 🫣🙈, but @MartinHoldrege solved, and his changes are in the dev version -> https://github.com/r-spatial/rgee/pull/251/commits/9f6eeb00d5f26c48b7c95aa6c8a4d2feee04c795

Can you confirm us that this bug also occurs if you install the latest version?
```r
remotes::install_github("r-spatial/rgee")
```

**Comment by jwilliamrozelle** [comment] 2022-06-24 01:21
Sorry, I was using the latest version on CRAN. I'll get back to you if I use the github version and still have an issue!

**Comment by csaybar** [comment] 2022-10-01 20:42
I'll close this issue for now because I can't reproduce this issue, if someone gets the same error, please re-opened it.

**Closed by csaybar** 2022-10-01 20:42 UTC
Labels: bug
